// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action_log.sql

package qx

import (
	"context"
)

const CreateActionLog = `-- name: CreateActionLog :one
INSERT INTO action_log (agent_id, message, category, created_at, updated_at)
VALUES (?, ?, ?,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, agent_id, message, category, created_at, updated_at
`

type CreateActionLogParams struct {
	AgentID  string `json:"agent_id"`
	Message  string `json:"message"`
	Category string `json:"category"`
}

func (q *Queries) CreateActionLog(ctx context.Context, arg CreateActionLogParams) (ActionLog, error) {
	row := q.db.QueryRowContext(ctx, CreateActionLog, arg.AgentID, arg.Message, arg.Category)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Message,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteActionLog = `-- name: DeleteActionLog :exec
DELETE FROM action_log WHERE id = ?1
`

func (q *Queries) DeleteActionLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteActionLog, id)
	return err
}

const GetActionLogByID = `-- name: GetActionLogByID :one
SELECT id, agent_id, message, category, created_at, updated_at FROM action_log WHERE id = ? LIMIT 1
`

func (q *Queries) GetActionLogByID(ctx context.Context, id int64) (ActionLog, error) {
	row := q.db.QueryRowContext(ctx, GetActionLogByID, id)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Message,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAllActionLogs = `-- name: GetAllActionLogs :many
SELECT id, agent_id, message, category, created_at, updated_at FROM action_log
`

func (q *Queries) GetAllActionLogs(ctx context.Context) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, GetAllActionLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Message,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
