// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action_log.sql

package qx

import (
	"context"
	"database/sql"
)

const CountActionLogs = `-- name: CountActionLogs :one
SELECT COUNT(*) AS count
FROM action_log
WHERE ? IS NULL OR agent_id = ?
`

type CountActionLogsParams struct {
	Column1 interface{} `json:"column_1"`
	AgentID string      `json:"agent_id"`
}

func (q *Queries) CountActionLogs(ctx context.Context, arg CountActionLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountActionLogs, arg.Column1, arg.AgentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateActionLog = `-- name: CreateActionLog :one
INSERT INTO action_log (agent_id, message, category, created_at, updated_at)
VALUES (?, ?, ?,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, agent_id, message, category, created_at, updated_at
`

type CreateActionLogParams struct {
	AgentID  string `json:"agent_id"`
	Message  string `json:"message"`
	Category string `json:"category"`
}

func (q *Queries) CreateActionLog(ctx context.Context, arg CreateActionLogParams) (ActionLog, error) {
	row := q.db.QueryRowContext(ctx, CreateActionLog, arg.AgentID, arg.Message, arg.Category)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Message,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteActionLog = `-- name: DeleteActionLog :exec
DELETE FROM action_log WHERE id = ?1
`

func (q *Queries) DeleteActionLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteActionLog, id)
	return err
}

const GetActionLogByID = `-- name: GetActionLogByID :one
SELECT id, agent_id, message, category, created_at, updated_at FROM action_log WHERE id = ? LIMIT 1
`

func (q *Queries) GetActionLogByID(ctx context.Context, id int64) (ActionLog, error) {
	row := q.db.QueryRowContext(ctx, GetActionLogByID, id)
	var i ActionLog
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Message,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAllActionLogs = `-- name: GetAllActionLogs :many
SELECT id, agent_id, message, category, created_at, updated_at FROM action_log 
WHERE 
    (? IS NULL OR agent_id = ?)
  AND
    (? IS NULL OR category = ?)
  AND 
    ( ? IS NULL OR created_at >= ? )
  AND
    ( ? IS NULL OR created_at <= ? )
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetAllActionLogsParams struct {
	Column1     interface{}  `json:"column_1"`
	AgentID     string       `json:"agent_id"`
	Column3     interface{}  `json:"column_3"`
	Category    string       `json:"category"`
	Column5     interface{}  `json:"column_5"`
	CreatedAt   sql.NullTime `json:"created_at"`
	Column7     interface{}  `json:"column_7"`
	CreatedAt_2 sql.NullTime `json:"created_at_2"`
	Limit       int64        `json:"limit"`
	Offset      int64        `json:"offset"`
}

func (q *Queries) GetAllActionLogs(ctx context.Context, arg GetAllActionLogsParams) ([]ActionLog, error) {
	rows, err := q.db.QueryContext(ctx, GetAllActionLogs,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.Category,
		arg.Column5,
		arg.CreatedAt,
		arg.Column7,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionLog{}
	for rows.Next() {
		var i ActionLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Message,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
