// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent.sql

package qx

import (
	"context"
	"database/sql"
)

const CreateAgent = `-- name: CreateAgent :one
INSERT INTO agent (id, name, description, agent_type_id, config, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, description, agent_type_id, config, created_at, updated_at
`

type CreateAgentParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	AgentTypeID int64  `json:"agent_type_id"`
	Config      string `json:"config"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, CreateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AgentTypeID,
		arg.Config,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AgentTypeID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agent WHERE id = ?1
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, DeleteAgent, id)
	return err
}

const GetAgentByID = `-- name: GetAgentByID :one
SELECT id, name, description, agent_type_id, config, created_at, updated_at FROM agent WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgentByID(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, GetAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AgentTypeID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAllAgents = `-- name: GetAllAgents :many
SELECT id, name, description, agent_type_id, config, created_at, updated_at FROM agent
`

func (q *Queries) GetAllAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AgentTypeID,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PatchAgent = `-- name: PatchAgent :one
UPDATE agent
SET
  name   = COALESCE(?1, name),
  description = COALESCE(?2, description),
  config = COALESCE(?3, config),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?4
RETURNING id, name, description, agent_type_id, config, created_at, updated_at
`

type PatchAgentParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Config      sql.NullString `json:"config"`
	ID          string         `json:"id"`
}

func (q *Queries) PatchAgent(ctx context.Context, arg PatchAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, PatchAgent,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AgentTypeID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
