// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_type.sql

package qx

import (
	"context"
)

const CreateAgentType = `-- name: CreateAgentType :one
INSERT INTO agent_type (name, description, created_at, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, description, created_at, updated_at
`

type CreateAgentTypeParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateAgentType(ctx context.Context, arg CreateAgentTypeParams) (AgentType, error) {
	row := q.db.QueryRowContext(ctx, CreateAgentType, arg.Name, arg.Description)
	var i AgentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteAgentType = `-- name: DeleteAgentType :exec
DELETE FROM agent_type WHERE id = ?
`

func (q *Queries) DeleteAgentType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAgentType, id)
	return err
}

const GetAgentTypeByID = `-- name: GetAgentTypeByID :one
SELECT id, name, description, created_at, updated_at FROM agent_type WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgentTypeByID(ctx context.Context, id int64) (AgentType, error) {
	row := q.db.QueryRowContext(ctx, GetAgentTypeByID, id)
	var i AgentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAllAgentTypes = `-- name: GetAllAgentTypes :many
SELECT id, name, description, created_at, updated_at FROM agent_type
`

func (q *Queries) GetAllAgentTypes(ctx context.Context) ([]AgentType, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAgentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentType{}
	for rows.Next() {
		var i AgentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PatchAgentType = `-- name: PatchAgentType :one
UPDATE agent_type
SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, created_at, updated_at
`

type PatchAgentTypeParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

func (q *Queries) PatchAgentType(ctx context.Context, arg PatchAgentTypeParams) (AgentType, error) {
	row := q.db.QueryRowContext(ctx, PatchAgentType, arg.Name, arg.Description, arg.ID)
	var i AgentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
