// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: asset_file.sql

package qx

import (
	"context"
	"database/sql"
	"time"
)

const CountAssetFiles = `-- name: CountAssetFiles :one
SELECT COUNT(*) AS count
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
`

type CountAssetFilesParams struct {
	Column1  interface{} `json:"column_1"`
	AgentID  string      `json:"agent_id"`
	Column3  interface{} `json:"column_3"`
	CameraID string      `json:"camera_id"`
}

func (q *Queries) CountAssetFiles(ctx context.Context, arg CountAssetFilesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAssetFiles,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAssetFile = `-- name: CreateAssetFile :one
INSERT INTO asset_file (agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
`

type CreateAssetFileParams struct {
	AgentID   string    `json:"agent_id"`
	CameraID  string    `json:"camera_id"`
	Location  string    `json:"location"`
	Timestamp time.Time `json:"timestamp"`
	UniqueID  string    `json:"unique_id"`
	FileName  string    `json:"file_name"`
	FileSize  int64     `json:"file_size"`
	FileType  string    `json:"file_type"`
}

func (q *Queries) CreateAssetFile(ctx context.Context, arg CreateAssetFileParams) (AssetFile, error) {
	row := q.db.QueryRowContext(ctx, CreateAssetFile,
		arg.AgentID,
		arg.CameraID,
		arg.Location,
		arg.Timestamp,
		arg.UniqueID,
		arg.FileName,
		arg.FileSize,
		arg.FileType,
	)
	var i AssetFile
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CameraID,
		&i.Location,
		&i.Timestamp,
		&i.UniqueID,
		&i.FileName,
		&i.FileSize,
		&i.FileType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteAssetFile = `-- name: DeleteAssetFile :exec
DELETE FROM asset_file WHERE id = ?
`

func (q *Queries) DeleteAssetFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAssetFile, id)
	return err
}

const GetAllAssetFiles = `-- name: GetAllAssetFiles :many
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
  AND 
    ( ? IS NULL OR timestamp >= ? )
  AND
    ( ? IS NULL OR timestamp <= ? )
ORDER BY timestamp ASC
LIMIT ? OFFSET ?
`

type GetAllAssetFilesParams struct {
	Column1     interface{} `json:"column_1"`
	AgentID     string      `json:"agent_id"`
	Column3     interface{} `json:"column_3"`
	CameraID    string      `json:"camera_id"`
	Column5     interface{} `json:"column_5"`
	Timestamp   time.Time   `json:"timestamp"`
	Column7     interface{} `json:"column_7"`
	Timestamp_2 time.Time   `json:"timestamp_2"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) GetAllAssetFiles(ctx context.Context, arg GetAllAssetFilesParams) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFiles,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
		arg.Column5,
		arg.Timestamp,
		arg.Column7,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllAssetFilesFileNameAsc = `-- name: GetAllAssetFilesFileNameAsc :many
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
  AND 
    ( ? IS NULL OR timestamp >= ? )
  AND
    ( ? IS NULL OR timestamp <= ? )
ORDER BY file_name ASC
LIMIT ? OFFSET ?
`

type GetAllAssetFilesFileNameAscParams struct {
	Column1     interface{} `json:"column_1"`
	AgentID     string      `json:"agent_id"`
	Column3     interface{} `json:"column_3"`
	CameraID    string      `json:"camera_id"`
	Column5     interface{} `json:"column_5"`
	Timestamp   time.Time   `json:"timestamp"`
	Column7     interface{} `json:"column_7"`
	Timestamp_2 time.Time   `json:"timestamp_2"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) GetAllAssetFilesFileNameAsc(ctx context.Context, arg GetAllAssetFilesFileNameAscParams) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFilesFileNameAsc,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
		arg.Column5,
		arg.Timestamp,
		arg.Column7,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllAssetFilesFileNameDesc = `-- name: GetAllAssetFilesFileNameDesc :many
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
  AND 
    ( ? IS NULL OR timestamp >= ? )
  AND
    ( ? IS NULL OR timestamp <= ? )
ORDER BY file_name DESC
LIMIT ? OFFSET ?
`

type GetAllAssetFilesFileNameDescParams struct {
	Column1     interface{} `json:"column_1"`
	AgentID     string      `json:"agent_id"`
	Column3     interface{} `json:"column_3"`
	CameraID    string      `json:"camera_id"`
	Column5     interface{} `json:"column_5"`
	Timestamp   time.Time   `json:"timestamp"`
	Column7     interface{} `json:"column_7"`
	Timestamp_2 time.Time   `json:"timestamp_2"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) GetAllAssetFilesFileNameDesc(ctx context.Context, arg GetAllAssetFilesFileNameDescParams) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFilesFileNameDesc,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
		arg.Column5,
		arg.Timestamp,
		arg.Column7,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllAssetFilesFileSizeAsc = `-- name: GetAllAssetFilesFileSizeAsc :many
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
  AND 
    ( ? IS NULL OR timestamp >= ? )
  AND
    ( ? IS NULL OR timestamp <= ? )
ORDER BY file_size ASC
LIMIT ? OFFSET ?
`

type GetAllAssetFilesFileSizeAscParams struct {
	Column1     interface{} `json:"column_1"`
	AgentID     string      `json:"agent_id"`
	Column3     interface{} `json:"column_3"`
	CameraID    string      `json:"camera_id"`
	Column5     interface{} `json:"column_5"`
	Timestamp   time.Time   `json:"timestamp"`
	Column7     interface{} `json:"column_7"`
	Timestamp_2 time.Time   `json:"timestamp_2"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) GetAllAssetFilesFileSizeAsc(ctx context.Context, arg GetAllAssetFilesFileSizeAscParams) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFilesFileSizeAsc,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
		arg.Column5,
		arg.Timestamp,
		arg.Column7,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllAssetFilesFileSizeDesc = `-- name: GetAllAssetFilesFileSizeDesc :many
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
  AND 
    ( ? IS NULL OR timestamp >= ? )
  AND
    ( ? IS NULL OR timestamp <= ? )
ORDER BY file_size DESC
LIMIT ? OFFSET ?
`

type GetAllAssetFilesFileSizeDescParams struct {
	Column1     interface{} `json:"column_1"`
	AgentID     string      `json:"agent_id"`
	Column3     interface{} `json:"column_3"`
	CameraID    string      `json:"camera_id"`
	Column5     interface{} `json:"column_5"`
	Timestamp   time.Time   `json:"timestamp"`
	Column7     interface{} `json:"column_7"`
	Timestamp_2 time.Time   `json:"timestamp_2"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) GetAllAssetFilesFileSizeDesc(ctx context.Context, arg GetAllAssetFilesFileSizeDescParams) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFilesFileSizeDesc,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
		arg.Column5,
		arg.Timestamp,
		arg.Column7,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllAssetFilesTimestampDesc = `-- name: GetAllAssetFilesTimestampDesc :many
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
  AND 
    ( ? IS NULL OR timestamp >= ? )
  AND
    ( ? IS NULL OR timestamp <= ? )
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type GetAllAssetFilesTimestampDescParams struct {
	Column1     interface{} `json:"column_1"`
	AgentID     string      `json:"agent_id"`
	Column3     interface{} `json:"column_3"`
	CameraID    string      `json:"camera_id"`
	Column5     interface{} `json:"column_5"`
	Timestamp   time.Time   `json:"timestamp"`
	Column7     interface{} `json:"column_7"`
	Timestamp_2 time.Time   `json:"timestamp_2"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) GetAllAssetFilesTimestampDesc(ctx context.Context, arg GetAllAssetFilesTimestampDescParams) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFilesTimestampDesc,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
		arg.Column5,
		arg.Timestamp,
		arg.Column7,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllAssetFilesUniqueIdAsc = `-- name: GetAllAssetFilesUniqueIdAsc :many
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
  AND 
    ( ? IS NULL OR timestamp >= ? )
  AND
    ( ? IS NULL OR timestamp <= ? )
ORDER BY unique_id ASC
LIMIT ? OFFSET ?
`

type GetAllAssetFilesUniqueIdAscParams struct {
	Column1     interface{} `json:"column_1"`
	AgentID     string      `json:"agent_id"`
	Column3     interface{} `json:"column_3"`
	CameraID    string      `json:"camera_id"`
	Column5     interface{} `json:"column_5"`
	Timestamp   time.Time   `json:"timestamp"`
	Column7     interface{} `json:"column_7"`
	Timestamp_2 time.Time   `json:"timestamp_2"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) GetAllAssetFilesUniqueIdAsc(ctx context.Context, arg GetAllAssetFilesUniqueIdAscParams) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFilesUniqueIdAsc,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
		arg.Column5,
		arg.Timestamp,
		arg.Column7,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllAssetFilesUniqueIdDesc = `-- name: GetAllAssetFilesUniqueIdDesc :many
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
FROM asset_file
WHERE
    ( ? IS NULL OR agent_id = ? )
  AND
    ( ? IS NULL OR camera_id = ? )
  AND 
    ( ? IS NULL OR timestamp >= ? )
  AND
    ( ? IS NULL OR timestamp <= ? )
ORDER BY unique_id DESC
LIMIT ? OFFSET ?
`

type GetAllAssetFilesUniqueIdDescParams struct {
	Column1     interface{} `json:"column_1"`
	AgentID     string      `json:"agent_id"`
	Column3     interface{} `json:"column_3"`
	CameraID    string      `json:"camera_id"`
	Column5     interface{} `json:"column_5"`
	Timestamp   time.Time   `json:"timestamp"`
	Column7     interface{} `json:"column_7"`
	Timestamp_2 time.Time   `json:"timestamp_2"`
	Limit       int64       `json:"limit"`
	Offset      int64       `json:"offset"`
}

func (q *Queries) GetAllAssetFilesUniqueIdDesc(ctx context.Context, arg GetAllAssetFilesUniqueIdDescParams) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFilesUniqueIdDesc,
		arg.Column1,
		arg.AgentID,
		arg.Column3,
		arg.CameraID,
		arg.Column5,
		arg.Timestamp,
		arg.Column7,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAssetFileByID = `-- name: GetAssetFileByID :one
SELECT id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at FROM asset_file WHERE id = ? LIMIT 1
`

func (q *Queries) GetAssetFileByID(ctx context.Context, id int64) (AssetFile, error) {
	row := q.db.QueryRowContext(ctx, GetAssetFileByID, id)
	var i AssetFile
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CameraID,
		&i.Location,
		&i.Timestamp,
		&i.UniqueID,
		&i.FileName,
		&i.FileSize,
		&i.FileType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const PatchAssetFile = `-- name: PatchAssetFile :one
UPDATE asset_file
SET
  camera_id   = COALESCE(?1, camera_id),
  location    = COALESCE(?2, location),
  timestamp   = COALESCE(?3, timestamp),
  unique_id   = COALESCE(?4, unique_id),
  file_name   = COALESCE(?5, file_name),
  file_size   = COALESCE(?6, file_size),
  updated_at  = CURRENT_TIMESTAMP
WHERE id = ?7
RETURNING id, agent_id, camera_id, location, timestamp, unique_id, file_name, file_size, file_type, created_at, updated_at
`

type PatchAssetFileParams struct {
	CameraID  sql.NullString `json:"camera_id"`
	Location  sql.NullString `json:"location"`
	Timestamp sql.NullTime   `json:"timestamp"`
	UniqueID  sql.NullString `json:"unique_id"`
	FileName  sql.NullString `json:"file_name"`
	FileSize  sql.NullInt64  `json:"file_size"`
	ID        int64          `json:"id"`
}

func (q *Queries) PatchAssetFile(ctx context.Context, arg PatchAssetFileParams) (AssetFile, error) {
	row := q.db.QueryRowContext(ctx, PatchAssetFile,
		arg.CameraID,
		arg.Location,
		arg.Timestamp,
		arg.UniqueID,
		arg.FileName,
		arg.FileSize,
		arg.ID,
	)
	var i AssetFile
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CameraID,
		&i.Location,
		&i.Timestamp,
		&i.UniqueID,
		&i.FileName,
		&i.FileSize,
		&i.FileType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
