// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_file.sql

package qx

import (
	"context"
	"database/sql"
	"time"
)

const CreateAssetFile = `-- name: CreateAssetFile :one
INSERT INTO asset_file (camera_id, location, timestamp, unique_id, file_name, file_size, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, camera_id, location, timestamp, unique_id, file_name, file_size, created_at, updated_at
`

type CreateAssetFileParams struct {
	CameraID  string    `json:"camera_id"`
	Location  string    `json:"location"`
	Timestamp time.Time `json:"timestamp"`
	UniqueID  string    `json:"unique_id"`
	FileName  string    `json:"file_name"`
	FileSize  int64     `json:"file_size"`
}

func (q *Queries) CreateAssetFile(ctx context.Context, arg CreateAssetFileParams) (AssetFile, error) {
	row := q.db.QueryRowContext(ctx, CreateAssetFile,
		arg.CameraID,
		arg.Location,
		arg.Timestamp,
		arg.UniqueID,
		arg.FileName,
		arg.FileSize,
	)
	var i AssetFile
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Location,
		&i.Timestamp,
		&i.UniqueID,
		&i.FileName,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteAssetFile = `-- name: DeleteAssetFile :exec
DELETE FROM asset_file WHERE id = ?
`

func (q *Queries) DeleteAssetFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAssetFile, id)
	return err
}

const GetAllAssetFiles = `-- name: GetAllAssetFiles :many
SELECT id, camera_id, location, timestamp, unique_id, file_name, file_size, created_at, updated_at FROM asset_file
`

func (q *Queries) GetAllAssetFiles(ctx context.Context) ([]AssetFile, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAssetFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetFile{}
	for rows.Next() {
		var i AssetFile
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Location,
			&i.Timestamp,
			&i.UniqueID,
			&i.FileName,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAssetFileByID = `-- name: GetAssetFileByID :one
SELECT id, camera_id, location, timestamp, unique_id, file_name, file_size, created_at, updated_at FROM asset_file WHERE id = ? LIMIT 1
`

func (q *Queries) GetAssetFileByID(ctx context.Context, id int64) (AssetFile, error) {
	row := q.db.QueryRowContext(ctx, GetAssetFileByID, id)
	var i AssetFile
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Location,
		&i.Timestamp,
		&i.UniqueID,
		&i.FileName,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const PatchAssetFile = `-- name: PatchAssetFile :one
UPDATE asset_file
SET
  camera_id   = COALESCE(?1, camera_id),
  location    = COALESCE(?2, location),
  timestamp   = COALESCE(?3, timestamp),
  unique_id   = COALESCE(?4, unique_id),
  file_name   = COALESCE(?5, file_name),
  file_size   = COALESCE(?6, file_size),
  updated_at  = CURRENT_TIMESTAMP
WHERE id = ?7
RETURNING id, camera_id, location, timestamp, unique_id, file_name, file_size, created_at, updated_at
`

type PatchAssetFileParams struct {
	CameraID  sql.NullString `json:"camera_id"`
	Location  sql.NullString `json:"location"`
	Timestamp sql.NullTime   `json:"timestamp"`
	UniqueID  sql.NullString `json:"unique_id"`
	FileName  sql.NullString `json:"file_name"`
	FileSize  sql.NullInt64  `json:"file_size"`
	ID        int64          `json:"id"`
}

func (q *Queries) PatchAssetFile(ctx context.Context, arg PatchAssetFileParams) (AssetFile, error) {
	row := q.db.QueryRowContext(ctx, PatchAssetFile,
		arg.CameraID,
		arg.Location,
		arg.Timestamp,
		arg.UniqueID,
		arg.FileName,
		arg.FileSize,
		arg.ID,
	)
	var i AssetFile
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Location,
		&i.Timestamp,
		&i.UniqueID,
		&i.FileName,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
