// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package qx

import (
	"database/sql"
	"time"
)

type ActionLog struct {
	ID        int64        `json:"id"`
	AgentID   string       `json:"agent_id"`
	Message   string       `json:"message"`
	Category  string       `json:"category"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Agent struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	AgentTypeID int64        `json:"agent_type_id"`
	Config      string       `json:"config"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type AgentType struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type AssetFile struct {
	ID        int64        `json:"id"`
	CameraID  string       `json:"camera_id"`
	Location  string       `json:"location"`
	Timestamp time.Time    `json:"timestamp"`
	UniqueID  string       `json:"unique_id"`
	FileName  string       `json:"file_name"`
	FileSize  int64        `json:"file_size"`
	FileType  string       `json:"file_type"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type GooseDbVersion struct {
	ID        int64        `json:"id"`
	VersionID int64        `json:"version_id"`
	IsApplied int64        `json:"is_applied"`
	Tstamp    sql.NullTime `json:"tstamp"`
}

type SqliteSequence struct {
	Name interface{} `json:"name"`
	Seq  interface{} `json:"seq"`
}
