// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package qx

import (
	"context"
)

type Querier interface {
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateAgentType(ctx context.Context, arg CreateAgentTypeParams) (AgentType, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteAgentType(ctx context.Context, id int64) error
	GetAgentByID(ctx context.Context, id string) (Agent, error)
	GetAgentTypeByID(ctx context.Context, id int64) (AgentType, error)
	GetAllAgentTypes(ctx context.Context) ([]AgentType, error)
	GetAllAgents(ctx context.Context) ([]Agent, error)
	PatchAgent(ctx context.Context, arg PatchAgentParams) (Agent, error)
	PatchAgentType(ctx context.Context, arg PatchAgentTypeParams) (AgentType, error)
}

var _ Querier = (*Queries)(nil)
