// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package qx

import (
	"context"
)

type Querier interface {
	CountActionLogs(ctx context.Context, arg CountActionLogsParams) (int64, error)
	CountAssetFiles(ctx context.Context, arg CountAssetFilesParams) (int64, error)
	CreateActionLog(ctx context.Context, arg CreateActionLogParams) (ActionLog, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateAgentType(ctx context.Context, arg CreateAgentTypeParams) (AgentType, error)
	CreateAssetFile(ctx context.Context, arg CreateAssetFileParams) (AssetFile, error)
	DeleteActionLog(ctx context.Context, id int64) error
	DeleteAgent(ctx context.Context, id string) error
	DeleteAgentType(ctx context.Context, id int64) error
	DeleteAssetFile(ctx context.Context, id int64) error
	GetActionLogByID(ctx context.Context, id int64) (ActionLog, error)
	GetAgentByID(ctx context.Context, id string) (Agent, error)
	GetAgentTypeByID(ctx context.Context, id int64) (AgentType, error)
	GetAllActionLogs(ctx context.Context, arg GetAllActionLogsParams) ([]ActionLog, error)
	GetAllAgentTypes(ctx context.Context) ([]AgentType, error)
	GetAllAgents(ctx context.Context) ([]Agent, error)
	GetAllAssetFiles(ctx context.Context, arg GetAllAssetFilesParams) ([]AssetFile, error)
	GetAllAssetFilesFileNameAsc(ctx context.Context, arg GetAllAssetFilesFileNameAscParams) ([]AssetFile, error)
	GetAllAssetFilesFileNameDesc(ctx context.Context, arg GetAllAssetFilesFileNameDescParams) ([]AssetFile, error)
	GetAllAssetFilesFileSizeAsc(ctx context.Context, arg GetAllAssetFilesFileSizeAscParams) ([]AssetFile, error)
	GetAllAssetFilesFileSizeDesc(ctx context.Context, arg GetAllAssetFilesFileSizeDescParams) ([]AssetFile, error)
	GetAllAssetFilesTimestampDesc(ctx context.Context, arg GetAllAssetFilesTimestampDescParams) ([]AssetFile, error)
	GetAllAssetFilesUniqueIdAsc(ctx context.Context, arg GetAllAssetFilesUniqueIdAscParams) ([]AssetFile, error)
	GetAllAssetFilesUniqueIdDesc(ctx context.Context, arg GetAllAssetFilesUniqueIdDescParams) ([]AssetFile, error)
	GetAssetFileByID(ctx context.Context, id int64) (AssetFile, error)
	PatchAgent(ctx context.Context, arg PatchAgentParams) (Agent, error)
	PatchAgentType(ctx context.Context, arg PatchAgentTypeParams) (AgentType, error)
	PatchAssetFile(ctx context.Context, arg PatchAssetFileParams) (AssetFile, error)
}

var _ Querier = (*Queries)(nil)
