services:
  kerberos-agent:
    container_name: artincam # must be unique per agent
    image: "kerberos/agent:v3.3.8"
    ports:
      # The first number (before ":") is the port on your host machine.
      # The second number (after ":") is the port inside the container.
      # Example: "5000:80" means you can access the UI at http://localhost:5000.
      # 
      # ❗ Important:
      # - Only modify the **left side** (host port). Keep "80" unchanged.
      # - Use port numbers **3000–65535** to avoid conflicts.
      # - Each agent must have a unique host port (e.g., "4000:80" and "4001:80").
      - "4000:80"

    volumes:
      # Maps local directories to container directories.
      # Changes made in these folders persist outside the container.
      #
      # ❗ Important:
      # - Only modify the **left side** (host path). The right side must stay the same.
      # - Example: "./agent/config:/home/agent/data/config" keeps configuration files persistent.
      - ./agent/config:/home/agent/data/config
      - ./agent/recordings:/home/agent/data/recordings


  # You can have multiple agents. they must be named different and have different directory.
  # kerberos-agent:
  #   image: "kerberos/agent:v3.3.8"
  #   ports:
  #     - "4000:80" 

  #   volumes:
  #     - ./agent/config:/home/agent/data/config
  #     - ./agent/recordings:/home/agent/data/recordings
