# Starts the Docker Compose services in detached mode (runs in the background)
up: down
	sudo docker compose up -d

# Stops and removes the Docker Compose services (containers only, data remains)
down:
	sudo docker compose down
